services:
  auth-service:
    image: auth-service:latest
    container_name: auth-service-container
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    # depends_on:
    #   - mongodb
    #   - rabbitmq
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/backend-app/src
      - ./package.json:/usr/src/backend-app/package.json
      - ./package-lock.json:/usr/src/backend-app/package-lock.json
  # mongodb:
  #   image: mongo:7.0
  #   container_name: mongodb
  #   restart: unless-stopped
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongo_data:/data/db

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   restart: unless-stopped
  #   ports:
  #     - '5672:5672'
  #     - '15672:15672'
  #   environment:
  #     RABBITMQ_DEFAULT_USER: myuser
  #     RABBITMQ_DEFAULT_PASS: mypassword
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq # For persistent data
  #     - rabbitmq_logs:/var/log/rabbitmq # For persistent logs


  # redis:
  #   image: redis:7.2-alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis_data:/data

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - '9091:9090'
  #   depends_on:
  #     - auth-service

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - '3001:3000'
  #   depends_on:
  #     - prometheus

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_logs:
