import { eq, and, sql } from 'drizzle-orm';
import { db } from '../connections/connectDB';
import { users, type User, type NewUser } from '../db/models/userModel';
import dayjs from 'dayjs';
import { PgColumn } from 'drizzle-orm/pg-core';

export const registerUser = async (payload: NewUser): Promise<User> => {
  // Ensure 'id' is not part of the payload if it's auto-generated by $defaultFn
  // If 'id' is part of NewUser and not meant to be set manually, adjust NewUser or payload type.
  // Assuming NewUser is correctly defined for insert operations.
  const [user] = await db.insert(users).values(payload).returning();
  return user;
};

export const findUserById = async (
  id: string,
  selectColumns?: (keyof User)[]
): Promise<User | null> => {
  let query = db.select().from(users).where(eq(users.id, id)).limit(1);

  if (selectColumns && selectColumns.length > 0) {
    const selection: Record<string, PgColumn> = {};
    selectColumns.forEach((colName) => {
      if (users[colName]) {
        selection[colName as string] = users[colName] as PgColumn;
      }
    });
    query = db.select(selection).from(users).where(eq(users.id, id)).limit(1);
  }

  const [user] = await query;
  return user || null;
};

export const findByIdWithPassword = async (id: string): Promise<User | null> =>
  // This will select all columns by default, including password
  await findUserById(id);

export const findUserByEmailAddress = async (
  emailAddress: string,
  selectColumns?: (keyof User)[]
): Promise<User | null> => {
  let query = db.select().from(users).where(eq(users.emailAddress, emailAddress)).limit(1);

  if (selectColumns && selectColumns.length > 0) {
    const selection: Record<string, PgColumn> = {};
    selectColumns.forEach((colName) => {
      if (users[colName]) {
        selection[colName as string] = users[colName] as PgColumn;
      }
    });
    query = db.select(selection).from(users).where(eq(users.emailAddress, emailAddress)).limit(1);
  }
  const [user] = await query;
  return user || null;
};

export const findUserByConfirmationTokenAndCode = async (
  token: string,
  code: string
): Promise<User | null> => {
  const [user] = await db
    .select()
    .from(users)
    .where(
      and(
        sql`${users.accountConfirmation}->>'token' = ${token}`,
        sql`${users.accountConfirmation}->>'code' = ${code}`
      )
    )
    .limit(1);
  return user || null;
};

export const findByResetToken = async (token: string): Promise<User | null> => {
  const [user] = await db
    .select()
    .from(users)
    .where(sql`${users.passwordReset}->>'token' = ${token}`)
    .limit(1);
  return user || null;
};

export const updateUserById = async (
  userId: string,
  payload: Partial<Omit<NewUser, 'id' | 'createdAt' | 'updatedAt'>> & { updatedAt?: Date }
): Promise<User | null> => {
  // Ensure 'updatedAt' is always set
  const updatePayload = {
    ...payload,
    updatedAt: new Date()
  };

  const [updatedUser] = await db
    .update(users)
    .set(updatePayload)
    .where(eq(users.id, userId))
    .returning();

  return updatedUser || null;
};

export const updateUserLastLogin = async (userId: string): Promise<User | null> => {
  const [user] = await db
    .update(users)
    .set({
      lastLoginAt: dayjs().utc().toDate(),
      updatedAt: new Date()
    })
    .where(eq(users.id, userId))
    .returning();
  return user || null;
};
